
CREATE TABLE IF NOT EXISTS Invoke (
    nick TEXT NOT NULL PRIMARY KEY,
    date DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS Link (
    id integer NOT NULL PRIMARY KEY,
    user TEXT,
    url TEXT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    title TEXT);

CREATE TABLE IF NOT EXISTS Memo (
    id integer NOT NULL PRIMARY KEY,
    user_to TEXT,
    user_from TEXT,
    message TEXT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS Picture (
    id INTEGER NOT NULL PRIMARY KEY,
    tag TEXT,
    url TEXT,
    nick TEXT,
    nsfw INTEGER,
    date DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS Quote (
    id integer NOT NULL PRIMARY KEY,
    user TEXT,
    content TEXT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS User (
    nick TEXT NOT NULL PRIMARY KEY,
    email TEXT);

